apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsaab-quantum-bank-frontend-deployment
  namespace: hsaab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsaab-quantum-bank-frontend-deployment
  template:
    metadata:
      labels:
        app: hsaab-quantum-bank-frontend-deployment
    spec:
      containers:
      - name: quantum-bank-1
        image: hsaab/quantum-bank:43
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
