apiVersion: v1
kind: Service
metadata:
  name: hsaab-quantum-bank-frontend-service
  namespace: hsaab
  labels:
    app: hsaab-quantum-bank-frontend-deployment
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hsaab-quantum-bank-frontend-deployment
