pipeline:
  name: dev
  identifier: dev
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build_test_and_run
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: install node modules
                  identifier: install_node_modules
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: build prod
                  identifier: build_prod
                  spec:
                    shell: Sh
                    command: npm build
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
