apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-react-app
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-react-app
            port:
              number: 80